version: "3"

services:
  bamboobot:
    build: .
    expose:
      - 3000 # Next.js default port
    environment:
      VIRTUAL_PORT: 3000 # tells nginx proxy what port the app is listening on
      VIRTUAL_HOST: ${PRODUCTION_HOST} # how to find your app from outside
      LETSENCRYPT_HOST: ${PRODUCTION_HOST} # same, but for https
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL} # contact for cert
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    volumes:
      # Persist uploaded templates and generated PDFs
      - ./data/temp_images:/app/public/temp_images
      - ./data/generated:/app/public/generated
      - ./data/template_images:/app/public/template_images
    networks:
      devtksg: # same network that our reverse proxy is on
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service with hot reload
  bamboobot-dev:
    build:
      context: .
      target: builder  # Use the builder stage for development
    expose:
      - 3000
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: ${DEV_HOST} # different subdomain for dev
      LETSENCRYPT_HOST: ${DEV_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules  # Prevent overwriting node_modules
      - /app/.next         # Prevent overwriting .next build cache
      # Persist uploaded templates and generated PDFs
      - ./data/temp_images:/app/public/temp_images
      - ./data/generated:/app/public/generated
      - ./data/template_images:/app/public/template_images
    command: npm run dev
    networks:
      devtksg:
    restart: always
    profiles:
      - dev  # Only start when using dev profile

networks:
  devtksg:
    external: true