version: "3"

services:
  bamboobot:
    build: .
    expose:
      - 3000 # Next.js default port
    environment:
      VIRTUAL_PORT: 3000 # tells nginx proxy what port the app is listening on
      VIRTUAL_HOST: ${PRODUCTION_HOST} # how to find your app from outside
      LETSENCRYPT_HOST: ${PRODUCTION_HOST} # same, but for https
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL} # contact for cert
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    volumes:
      # Persist uploaded templates and generated PDFs
      - ./data/temp_images:/app/public/temp_images
      - ./data/generated:/app/public/generated
      - ./data/template_images:/app/public/template_images
    networks:
      devtksg: # same network that our reverse proxy is on
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  devtksg:
    external: true