services:
  bamboobot-dev:
    build:
      context: .
      target: builder  # Use the builder stage for development
    expose:
      - 3000
    env_file:
      - .env  # Load environment variables from file
    environment:
      # These override any values from env_file
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: ${DEV_HOST} # different subdomain for dev
      NODE_ENV: development  # Force development mode
      NEXT_TELEMETRY_DISABLED: 1
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules  # Prevent overwriting node_modules
      - /app/.next         # Prevent overwriting .next build cache
      # Persist uploaded templates and generated PDFs
      - ./data/temp_images:/app/public/temp_images
      - ./data/generated:/app/public/generated
      - ./data/template_images:/app/public/template_images
    command: npm run dev
    networks:
      devtksg:
    restart: always

networks:
  devtksg:
    external: true