services:
  bamboobot:
    build: .
    expose:
      - 3000 # Next.js default port
    env_file:
      - .env  # Load environment variables from file
    environment:
      # These override any values from env_file
      VIRTUAL_PORT: 3000 # tells nginx proxy what port the app is listening on
      VIRTUAL_HOST: ${PRODUCTION_HOST} # how to find your app from outside
      NODE_ENV: production  # Force production mode
      NEXT_TELEMETRY_DISABLED: 1
    volumes:
      # Persist uploaded templates and generated PDFs
      - ./data/temp_images:/app/public/temp_images
      - ./data/generated:/app/public/generated
      - ./data/template_images:/app/public/template_images
    networks:
      devtksg: # same network that our reverse proxy is on
    restart: always

networks:
  devtksg:
    external: true